name: Docker Hub Mirror
description: |
  Mirror images from the Docker Hub to another registry. The images can be
  rerouted if necessary.
author: Emmanuel Frecon <efrecon+github@gmail.com>
branding:
  icon: upload
  color: blue

inputs:
  image:
    description: |
      The name of the image to mirror, e.g. alpine, or efrecon/reg-tags
    required: true
  registry:
    description: |
      The path of the destination registry. The default is to pick the GHCR and
      reroute under the repository.
    default: ghcr.io/${{ github.repository }}
  options:
    description: |
      Additional options to `mirror.sh` script, e.g. -v to print out
      additional verbose information. This is a semi-internal input and should
      only be used for debugging.
    required: false
    default: ""
  tags:
    description: |
      Regular expression to match against the tags of source image so they will
      be considered for mirroring.
    default: "[0-9]+(\.[0-9]+)+$"
  minver:
    description: |
      Minimal version (extracted from image tag) that the source image must have
      to be considered for mirroring.
    default: 0

runs:
  using: composite
  steps:
    -
      name: Image Mirror
      id: mirror
      shell: bash
      run: |
        ${{ github.action_path }}/mirror.sh \
          -t '${{ inputs.tags }}' \
          -m '${{ inputs.minver }}' \
          -r '${{ inputs.registry }}' \
          -v \
          ${{ inputs.options }} \
          -- \
            '${{ inputs.image }}'